project:
  details:
    note:
      title: "Note"
      description: "Lorem ipsum"
      type: text
      required: true
    categories:
      title: "Categories"
      description: "Lorem ipsum"
      type: tags
      required: false
