services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/src:/app/src
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
      - ./backend/logs:/app/logs
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  node_modules:
  postgresql-data:
