services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - 5432:5432

