services:
  frontend:
    build: 
      context: ../project-allocator-frontend
      dockerfile: Dockerfile.production
    ports:
      - 80:8080
    depends_on:
      - backend
  backend:
    build:
      context: ../project-allocator-backend
      dockerfile: Dockerfile.production
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgresql-data:
