apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: db
spec:
  application: project-allocator
  cloudResource:
    plan: azure-azurerm-postgresql
    variables:
      server_name: <SERVER_NAME>
      administrator_login: <ADMINISTRATOR_LOGIN>
      administrator_password: <ADMINISTRATOR_PASSWORD>
  key: storage
  name: db
  type: CloudResource
