apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: db
spec:
  application: project-allocator
  cloudResource:
    plan: azure-azurerm-postgresql
    variables:
      server_name: hcm1yi0kjus9nw1d
      administrator_login: twey0qq6pmeelopn
      administrator_password: FxHC3XMu9ZzhDbFWTKxjqG6mZCjWy4N3
  key: storage
  name: db
  type: CloudResource
