apiVersion: app.appvia.io/v2beta1
kind: AppComponent
metadata:
  name: frontend
spec:
  application: project-allocator
  container:
    containers:
      - image: ghcr.io/<REPOSITORY_OWNER>/project-allocator-frontend:refs-heads-main
        name: frontend-1
        ports:
          - containerPort: 8080
            name: frontend-1-0
            protocol: TCP
            expose: true
        securityContext:
          runAsGroup: 999
          runAsUser: 999
    expose:
      container: frontend-1
      port: 8080
    tls: true
  name: frontend
  type: Container
