name: Deploy Application

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: quay.io/appvia-wayfinder/wftoolbox:${{ vars.WAYFINDER_VERSION }}
      env:
        WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
        WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
        WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Apply Wayfinder Configuration
        run: |
          wf apply -f wayfinder/app.yaml
          wf apply -f wayfinder/env.yaml
          wf apply -f wayfinder/db.yaml
          wf apply -f wayfinder/backend.yaml
          wf apply -f wayfinder/frontend.yaml

      - name: Deploy Application
        run: |
          wf deploy app project-allocator dev --image-tag refs-heads-main --force

      - name: Patch Secret
        run: |
          # We need to give kubelet credentials to pull images from ghcr.io
          # this needs to be done using kubectl at the moment
          # but in a future version of Wayfinder we will be able to do this using wf
          namespace=${{ vars.WAYFINDER_WORKSPACE }}-project-allocator-dev
          wf access env project-allocator dev
          kubectl patch deployment frontend -n "$namespace" --patch "$(cat wayfinder/secret-patch.json)"
          kubectl patch deployment backend -n "$namespace" --patch "$(cat wayfinder/secret-patch.json)"

      - name: Patch Network Policy
        run: |
          wf access env project-allocator dev
          kubectl apply -f wayfinder/backend-policy.yaml

      - name: Patch Ingress
        run: |
          wf access env project-allocator dev
          kubectl patch ingress frontend-ingress --type json --patch "$(cat wayfinder/ingress-patch.json)"

      - name: Wait for Completion
        run: |
          wf access env project-allocator dev
          while true; do
            echo "Attempting in 10 seconds..."
            sleep 10
            frontend_running="$(kubectl get pods --selector=app.kubernetes.io/component=frontend --field-selector=status.phase=Running --output json | jq -j '.items | length')"
            backend_running="$(kubectl get pods --selector=app.kubernetes.io/component=backend --field-selector=status.phase=Running --output json | jq -j '.items | length')"
            db_not_succeeded="$(kubectl get pods --selector=app.kubernetes.io/component=db --field-selector=status.phase!=Succeeded --output json | jq -j '.items | length')"
            if [ "$frontend_running" -eq 0 ]; then
              echo "No frontend pods running."
              continue
            fi
            if [ "$backend_running" -eq 0 ]; then
              echo "No backend pods running."
              continue
            fi
            if [ "$db_not_succeeded" -gt 0 ]; then
              echo "Not all DB pods have succeeded."
              continue
            fi
            echo "Deployment successeful."
            break
          done

      - name: Print Application URL
        run: |
          wf access env project-allocator dev
          url="$(kubectl get ingress | tail -n 1 | tr -s ' ' | cut -d ' ' -f 3)"
          echo "Your application is deployed at: https://$url"
