name: Deploy Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    container:
      image: quay.io/appvia-wayfinder/wftoolbox:${{ vars.WAYFINDER_VERSION }}
      env:
        WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
        WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
        WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Apply Wayfinder Configuration
        run: |
          wf apply -f manifests/app.yaml
          wf apply -f manifests/env.yaml
          # Sed is not installed in Appvia's wftoolbox image.
          apk add --no-cache sed
          server_name=${{ secrets.DATABASE_SERVER_NAME }}
          administrator_login=${{ secrets.DATABASE_ADMINISTRATOR_LOGIN }}
          administrator_password=${{ secrets.DATABASE_ADMINISTRATOR_PASSWORD }}
          sed -i -e "s/<SERVER_NAME>/$server_name/g;s/<ADMINISTRATOR_LOGIN>/$administrator_login/g;s/<ADMINISTRATOR_PASSWORD>/$administrator_password/g" manifests/db.yaml
          wf apply -f manifests/db.yaml
          wf apply -f manifests/backend.yaml
          wf apply -f manifests/frontend.yaml

      - name: Deploy Application
        run: |
          frontend_tag="$(gh api orgs/${{ github.repository_owner }}/packages/container/project-allocator-frontend/versions | jq -r '.[0].metadata.container.tags[0]')"
          backend_tag="$(gh api orgs/${{ github.repository_owner }}/packages/container/project-allocator-backend/versions | jq -r '.[0].metadata.container.tags[0]')"
          wf deploy component project-allocator dev --component frontend --image-tag "$frontend_tag" --force
          wf deploy component project-allocator dev --component backend --image-tag "$backend_tag" --force
          wf deploy component project-allocator dev --component db --force

      - name: Patch Secret
        run: |
          # We need to give kubelet credentials to pull images from ghcr.io
          # this needs to be done using kubectl at the moment
          # but in a future version of Wayfinder we will be able to do this using wf
          namespace=${{ vars.WAYFINDER_WORKSPACE }}-project-allocator-dev
          wf access env project-allocator dev
          kubectl patch deployment frontend -n "$namespace" --patch "$(cat manifests/secret-patch.json)"
          kubectl patch deployment backend -n "$namespace" --patch "$(cat manifests/secret-patch.json)"

      - name: Patch Ingress
        run: |
          wf access env project-allocator dev
          kubectl patch ingress frontend-ingress --type json --patch "$(cat manifests/ingress-patch.json)"

      - name: Create Network Policy
        run: |
          wf access env project-allocator dev
          kubectl apply -f manifests/backend-policy.yaml

      - name: Wait for Completion
        run: |
          wf access env project-allocator dev
          # Bash is not installed in Appvia's wftoolbox image.
          apk add --no-cache bash
          bash .github/scripts/wait_deploy.sh

      - name: Print Application URL
        run: |
          wf access env project-allocator dev
          url="$(kubectl get ingress | tail -n 1 | tr -s ' ' | cut -d ' ' -f 3)"
          echo "Your application is deployed at: https://$url"
