name: Deploy Docker Image

on: [push]

jobs:
  push:
    # needs: test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
      sha-tag: sha-${{ github.sha }}
      ref-tag: sha-${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build tags
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.ref }},enable={{is_default_branch}}
            type=raw,value=${{ github.sha }},prefix=sha-,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push image
        uses: docker/build-push-action@v4
        id: docker-digest
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            ghcr.io/${{ github.repository }}:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest

    container:
      image: quay.io/appvia-wayfinder/wftoolbox:v2.1.2
      env:
        WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
        WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
        WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy application
        run: wf deploy app ${{ vars.WAYFINDER_APPLICATION }} ${{ vars.WAYFINDER_ENVIRONMENT }} --image-tag ${{ needs.push.outputs.sha-tag }}

      - name: Patch secret
        run: |
          # We need to give kubelet credentials to pull images from ghcr.io
          # this needs to be done using kubectl at the moment
          # but in a future version of Wayfinder we will be able to do this using wf
          namespace=${{ vars.WAYFINDER_WORKSPACE }}-${{ vars.WAYFINDER_APPLICATION }}-${{ vars.WAYFINDER_ENVIRONMENT }}
          wf access env ${{ vars.WAYFINDER_APPLICATION }} ${{ vars.WAYFINDER_ENVIRONMENT }}
          kubectl patch deployment ${{ vars.WAYFINDER_COMPONENT }} -n "$namespace" --patch '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"ghcr-login-secret"}]}}}}'
