name: Deploy Application

env:
  REGISTRY: ghcr.io

on:
  workflow_run:
    workflows: ["Backend CI", "Frontend CI"]
    types:
      - completed 

jobs:
  docker:
    if: github.ref == 'refs/heads/main' # Only run on 'main'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
    outputs:
      sha-tag: sha-${{ github.sha }}

    strategy:
      matrix:
        component: ["frontend", "backend"]

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build tags
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.component }}
          tags: |
            type=raw,value=${{ github.sha }},prefix=sha-,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: "{{ defaultContext  }}:${{ matrix.component }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: ${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.component }}:latest
