name: Deploy Application

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: quay.io/appvia-wayfinder/wftoolbox:v2.1.2
      env:
        WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
        WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
        WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Application
        run: wf deploy app ${{ vars.WAYFINDER_APPLICATION }} ${{ vars.WAYFINDER_ENVIRONMENT }} --image-tag refs-heads-main

      - name: Patch Secrets
        run: |
          # We need to give kubelet credentials to pull images from ghcr.io
          # this needs to be done using kubectl at the moment
          # but in a future version of Wayfinder we will be able to do this using wf
          namespace=${{ vars.WAYFINDER_WORKSPACE }}-${{ vars.WAYFINDER_APPLICATION }}-${{ vars.WAYFINDER_ENVIRONMENT }}
          wf access env ${{ vars.WAYFINDER_APPLICATION }} ${{ vars.WAYFINDER_ENVIRONMENT }}
          kubectl patch deployment ${{ vars.WAYFINDER_FRONTEND_COMPONENT }} -n "$namespace" --patch '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"ghcr-login-secret"}]}}}}'
          kubectl patch deployment ${{ vars.WAYFINDER_BACKEND_COMPONENT }} -n "$namespace" --patch '{"spec":{"template":{"spec":{"imagePullSecrets":[{"name":"ghcr-login-secret"}]}}}}'
