name: Destroy Application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: quay.io/appvia-wayfinder/wftoolbox:${{ vars.WAYFINDER_VERSION }}
      env:
        WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
        WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
        WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Destroy Application
        run: |
          wf deploy component project-allocator dev --component frontend --remove --force
          wf deploy component project-allocator dev --component backend --remove --force
          wf deploy component project-allocator dev --component db --remove --force

      - name: Wait for Completion
        run: |
          # Wait until there are no running pods in the namespace.
          wf access env project-allocator dev
          while true; do
            count="$(kubectl get pods --field-selector=status.phase==Running | wc -l | xargs)"
            if [ "$count" == 1 ]; then
              break
            fi
            sleep 10
          done
