name: Destroy Application

on:
  workflow_dispatch:

concurrency: destroy

jobs:
  destroy:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    container:
      image: quay.io/appvia-wayfinder/wftoolbox:${{ vars.WAYFINDER_VERSION }}
      env:
        WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
        WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
        WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          # These are not found in Appvia's wftoolbox image.
          apk add --no-cache bash sed

      - name: Get Kubernetes access
        run: |
          wf access env project-allocator dev

      - name: Clean pods
        run: |
          bash .github/scripts/clean_pods.sh '' status.phase!=Running,status.phase!=Pending

      - name: Destroy application
        run: |
          wf deploy component project-allocator dev --component frontend --remove --force
          wf deploy component project-allocator dev --component backend --remove --force
          wf deploy component project-allocator dev --component db --remove --force

      - name: Remove network policy
        run: |
          kubectl delete networkpolicy backend-ingress

      - name: Wait for completion
        run: |
          bash .github/scripts/wait_destroy.sh
