name: Destroy Application

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    container:
      image: quay.io/appvia-wayfinder/wftoolbox:${{ vars.WAYFINDER_VERSION }}
      env:
        WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
        WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
        WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Destroy Application
        run: |
          wf deploy component project-allocator dev --component frontend --remove --force
          wf deploy component project-allocator dev --component backend --remove --force
          wf deploy component project-allocator dev --component db --remove --force

      - name: Wait for Completion
        run: |
          wf access env project-allocator dev
          ./scripts/wait_destroy.sh
