name: Destroy Application

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    container:
      image: quay.io/appvia-wayfinder/wftoolbox:${{ vars.WAYFINDER_VERSION }}
      env:
        WAYFINDER_TOKEN: ${{ secrets.WAYFINDER_TOKEN }}
        WAYFINDER_SERVER: ${{ vars.WAYFINDER_SERVER }}
        WAYFINDER_WORKSPACE: ${{ vars.WAYFINDER_WORKSPACE }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Destroy Application
        run: |
          wf deploy component project-allocator dev --component frontend --remove --force
          wf deploy component project-allocator dev --component backend --remove --force
          wf deploy component project-allocator dev --component db --remove --force

      - name: Wait for Completion
        run: |
          wf access env project-allocator dev
          while true; do
            echo "Attempting in 10 seconds..."
            sleep 10
            pods_failed="$(kubectl get pods --field-selector=status.phase=Failed --output json | jq -j '.items | length')"
            pods_active="$(kubectl get pods --field-selector=status.phase!=Succeeded,status.phase!=Failed --output json | jq -j '.items | length')"
            if [ "$pods_failed" -gt 0 ]; then
              echo "Some pods have failed."
              break
            fi
            if [ "$pods_active" -eq 0 ]; then
              echo "All pods have been stopped."
              break
            fi
          done
