name: Frontend CD

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/${{ github.repository }}-frontend

on:
  push:
    paths:
      - "frontend/**"
      - "!**.md"
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Run Prettier formatter
        run: yarn run prettier --check --log-level debug --print-width 120 src/

  build-and-push-image:
    needs: format
    if: github.ref == 'refs/heads/main' # Only run on 'main'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: read
      packages: write
    outputs:
      sha-tag: sha-${{ github.sha }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build tags
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.IMAGE_NAME }} 
          tags: |
            type=raw,value=${{ github.sha }},prefix=sha-,enable={{is_default_branch}}
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push images
        uses: docker/build-push-action@v6
        with:
          context: "{{ defaultContext }}:frontend"
          build-args: BACKEND_URL=${{ vars.BACKEND_URL }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: ${{ env.IMAGE_NAME }}:latest

  deploy-via-tsuru:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    if: github.ref == 'refs/heads/main'
    env:
      TSURU_TOKEN: ${{ secrets.TSURU_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install tsuru CLI
        run: curl -fsSL "https://tsuru.io/get" | bash
      - name: Add impaas target
        run: tsuru target add impaas https://impaas.uk -s
      - name: Deploy app
        run: tsuru app deploy -i ${{ env.IMAGE_NAME }}:latest -a urop-project-allocator-frontend

