name: Frontend

on:
  push:
    paths:
      - "frontend/**"
      - "!**.md"
  pull_request:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.0

      - name: Install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run Prettier formatter
        run: |
          yarn run prettier --check --log-level debug --print-width 120 src/
